### ISSUE TITLE
fatal error: opencv2/imgproc.hpp: No such file or directory

### ISSUE THREAD

**Issue by samakanbour** [arthurflor23/text-segmentation#2]
Hello Arthur, cool library! I've been trying to install Python 3.7 + OpenCV 4.1, but when running **main.py** I keep getting the compile error "opencv2/imgproc.hpp: No such file or directory" on Windows. Would you know a workaround by any chance?

> C:\Python37\python.exe main.py -c -p --image ..\data\017.png
In file included from imgproc\cpp\Binarization.cpp:1:0:
imgproc\cpp\Binarization.hpp:2:10: fatal error: opencv2/imgproc.hpp: No such file or directory
 #include "opencv2/imgproc.hpp"
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from imgproc\cpp\LineSegmentation.cpp:1:0:
imgproc\cpp\LineSegmentation.hpp:3:10: fatal error: opencv2/imgproc.hpp: No such file or directory
 #include "opencv2/imgproc.hpp"
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from imgproc\cpp\Scanner.cpp:1:0:
imgproc\cpp\Scanner.hpp:2:10: fatal error: opencv2/imgproc.hpp: No such file or directory
 #include "opencv2/imgproc.hpp"
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from imgproc\cpp\WordSegmentation.cpp:1:0:
imgproc\cpp\WordSegmentation.hpp:2:10: fatal error: opencv2/imgproc.hpp: No such file or directory
 #include "opencv2/imgproc.hpp"
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from imgproc\cpp\main.cpp:1:0:
imgproc\cpp\Binarization.hpp:2:10: fatal error: opencv2/imgproc.hpp: No such file or directory
 #include "opencv2/imgproc.hpp"
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Preprocess compile error

>

**Comment by arthurflor23** [comment]
Hello and thanks!
This error is new to me, because I always used it on linux. I think it's the openCV installation (directory, maybe PATH), or g++.

Can you tell me how you installed?

Another approach is add *\`pkg-config opencv --cflags --libs\`* in g++ command (work it on linux), but I removed in the last commit (https://github.com/arthurflor23/text-segmentation/commit/4fb29b3b9231d254a1566f5ce387b55c70d4232e)

**Comment by longwall** [comment]
Hello, I'm having the same problem on Win10.
Conda,pyhton37. No way to solve.

Tried to replace #include opencv/LIBNAME.hpp  to  #include opencv/core/LIBNAME.hpp   - as suggested in similar issue in other project.
Didn't work

**Comment by arthurflor23** [comment]
Hi!
I saw that on Windows, opencv (c++) has to be downloaded the source code, compiled and added the system environment variables. Unfortunately I don't use windows to test this, but these are some help links I found:

a. https://www.hackeradam.com/installing-opencv-4-on-windows-10
b. https://www.deciphertechnic.com/install-opencv-with-visual-studio

I really found this process a bit laborious, however If you find any better solution, let me know, please.

**Comment by raviranjan0631** [comment]
hi arthur,
I had tried each and every approach to install opencv4 in ubuntu and i am able to built it successfully as install it but for some reason, I am unable to compile 
and I am getting the error undefined reference to
 `cv::imread(cv::String const&, int))`.
I had tried to compile with all the possible compilation ways but the error remains the same 
g++ -std=c++11 main.cpp -o test `pkg-config opencv3 --cflags --clibs`

So if possible can you push a docker image of your project such that we all can run your project or else can you refer me to some links where **I can learn to install opencv4 and compiles the code easily in UBUNTU** or can you provide a python alternative of this project as I am new to C++ but I am comfortable in python.

Please help me Arthur.

Thank you Arthur I hope you will help me out

**Comment by arthurflor23** [comment]
Hi!
I committed a support to opencv 3 right now from Ubuntu 19.04.
You only need install the package ``libopencv-dev`` from official repositories and run commands with ``python3``.

I tested from scratch here and needed some flags really ... this part is automatic now (cause windows doesn't accept those flags)

Let me know if help you, if not, I will see a VM to download.

**Comment by raviranjan0631** [comment]
hi arthur,
I had tried your above approach to solve the issue but the error remains same
 I am getting the error undefined reference to
cv::imread(cv::String const&, int))
if possible can you create a python equivalent of the project or a docker image of the project
Thank you

**Comment by arthurflor23** [comment]
Hi again, @raviranjan0631 

Initially I was going to develop the project in python, but some techniques like "Illumination Compensation" were very slow with high resolution images. The solution was to apply in c++. At the moment I'm in another project and I can't see the python port right now (although some techniques originally already are).

Anyway, I uploaded the docker [[here](https://drive.google.com/uc?id=14KftZl3SJZspaHmxtR3tQRPqRVTSm99v&export=download)] with Ubuntu 19.04 and the project running (/home/text-segmentation/src/).

If you want to run the project on another machine, I literally installed ubuntu, upgraded system and added the ``python3`` and ``libopencv-dev`` packages.

I hope this help you and thanks for the feedback!

**Comment by raviranjan0631** [comment]
hi arthur,
Thanks for sharing the docker image.
but can you share the docker image of your repository from your docker hub as the image you shared can run on your system only 
and to run other others image we need t pull it from their docker hub repository
Thank you

**Comment by raviranjan0631** [comment]
hi arthur,
got the trick to run your docker file
it's 
docker load < text-segmentation-docker

however can you send me the docker file of this image such that i can update my system with those configuration 
thank you
best regards
Ravi Ranjan

**Comment by raviranjan0631** [comment]
hi arthur, please send me the docker configuration file you had used to run this docker image as I want to modify it by installing with more packages

**Comment by arthurflor23** [comment]
Hi @raviranjan0631, sorry my delay
Here is the docker file content:

```
FROM ubuntu:19.04
MAINTAINER arthur
WORKDIR /
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y locales python3 libopencv-dev git \
    && rm -rf /var/lib/apt/lists/* \
    && localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
ENV LANG en_US.utf8
RUN git clone https://github.com/arthurflor23/text-segmentation /home/text-segmentation
```

Best!

**Comment by immoien** [comment]
Hello Arthur, I've been trying to install Python 3.7 + OpenCV 4.1, but when running main.py I keep getting the compile error "opencv2/imgproc.hpp: No such file or directory" on Ubuntu 18.04. Would you know a workaround by any chance? Screenshots attached.
![text-seg-2](https://user-images.githubusercontent.com/22579541/71994745-52c2c700-325f-11ea-8b89-e5b1a4156772.png)
![text-seg-3](https://user-images.githubusercontent.com/22579541/71994748-52c2c700-325f-11ea-9478-0ec99eb871bf.png)
![text-seg-4](https://user-images.githubusercontent.com/22579541/71994750-52c2c700-325f-11ea-8106-3cde267f2bf1.png)
![text-segmentation](https://user-images.githubusercontent.com/22579541/71994751-535b5d80-325f-11ea-9c6e-12400f626afc.png)

**Comment by arthurflor23** [comment]
> Hello Arthur, I've been trying to install Python 3.7 + OpenCV 4.1, but when running main.py I keep getting the compile error "opencv2/imgproc.hpp: No such file or directory" on Ubuntu 18.04. Would you know a workaround by any chance? Screenshots attached.

Hi, I think it must be the GCC version (7.x), try update to version 8+

**Comment by RyanRaskob** [comment]
In file included from imgproc\cpp\main.cpp:1:
imgproc\cpp\Binarization.hpp:2:10: fatal error: opencv2/imgproc.hpp: No such file or directory
 #include "opencv2/imgproc.hpp"

I'm  having the same issue a few others have. I've tried a ton of different ways to fix this issue with no luck, any suggestions? I am running this on windows 10. Thanks in advance

**Comment by arthurflor23** [comment]
Hi!
This problem is that windows doesn't recognize the opencv PATH.
Unfortunately, I don't know how works in windows indeed, but is necessary install and configure opencv 4+ and GCC 8+ compiler too.

**Comment by RyanRaskob** [comment]
I couldn't seem to get it to work. I spun up a VM with ubuntu and it seems
to be more promising. Your repo seems pretty awesome! I'm excited to test
it out

**Comment by RyanRaskob** [comment]
Do you happen to have a docker file that works with this program? I am
having trouble with opencv with ubuntu

**Comment by arthurflor23** [comment]
> Hi again, @raviranjan0631
> 
> Initially I was going to develop the project in python, but some techniques like "Illumination Compensation" were very slow with high resolution images. The solution was to apply in c++. At the moment I'm in another project and I can't see the python port right now (although some techniques originally already are).
> 
> Anyway, I uploaded the docker [[here](https://drive.google.com/uc?id=14KftZl3SJZspaHmxtR3tQRPqRVTSm99v&export=download)] with Ubuntu 19.04 and the project running (/home/text-segmentation/src/).
> 
> If you want to run the project on another machine, I literally installed ubuntu, upgraded system and added the `python3` and `libopencv-dev` packages.
> 
> I hope this help you and thanks for the feedback!

Hey, I uploaded in this post, with the project code in there

**Comment by RyanRaskob** [comment]
Thanks for the help! I was able to get my ubuntu working, I had to upgrade
gcc and g++ to version 8. I was getting an issue with the filesystem
include as well. The docker file will be useful for future usages. Very
much appreciated!
